# Generated by Django 6.0.2 on 2026-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert'), ('cocktail', 'Cocktail')], max_length=20)),
                ('preparation_time', models.IntegerField(help_text='Temps en minutes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('portions', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('utensils', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
